### ISSUE TITLE
IndexOutOfBoundsException preventing project load when a naming conflict occurs

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy-language-server#110]
To reproduce:

1. Create a file, `a.smithy`, with this content:

```smithy
$version: "2"

namespace a

operation HelloWorld {
    input := {
        @required
        name: String
    }
    output := {
        @required
        name: String
    }
}

```

2. Create another one, `b.smithy`, with this content:

```smithy
$version: "2"

namespace b

string Ignored

operation HelloWorld {
    input := {
        @required
        name: String
    }
    output := {
        @required
        name: String
    }
}
```

3. See errors. In your extension output panel you may see this:
```
java.lang.IndexOutOfBoundsException: Index 15 out of bounds for length 14
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at software.amazon.smithy.lsp.ext.FileCachingCollector.getNextEndMarker(FileCachingCollector.java:362)
	at software.amazon.smithy.lsp.ext.FileCachingCollector.getEndPosition(FileCachingCollector.java:421)
	at software.amazon.smithy.lsp.ext.FileCachingCollector.collectInlineInputOutputLocations(FileCachingCollector.java:153)
	at software.amazon.smithy.lsp.ext.FileCachingCollector.lambda$collectDefinitionLocations$0(FileCachingCollector.java:79)
```

I debugged this a little bit while minimizing, and it's pretty obvious to me now that the problem is the `HelloWorld` naming conflict - somewhere in the file caching collector there's some logic that doesn't disambiguate the two operations, while it should.

I'll investigate this further and work on a fix.

**Comment by kubukoz** [comment]
Looks like `collectInlineInputOutputLocations` thinks both `HelloWorldOutput`s are related to the operation in `b.smithy`:

<img width="1194" alt="image" src="https://github.com/awslabs/smithy-language-server/assets/894884/b3119672-ae10-4030-a627-fb509ea62bc3">

**Comment by kubukoz** [comment]
I have a test that reproduces this, but it only fails ~40% of the time (tested across 50 runs): https://github.com/disneystreaming/smithy-language-server/tree/iiobe-error-repro
