### ISSUE TITLE
Extension fails to start when connecting to the LSP server

### ISSUE THREAD

**Issue by daddykotex** [awslabs/smithy-language-server#57]
We have an extension for VS Code [here](https://github.com/disneystreaming/vscode-smithy). Currently it starts an LSP server that we publish under a fork of this repo.

But since you've published a version `0.1.0` for this repo, I figured we could use this instead of our fork. When I tried, the extension failed to load with the following error:

```
[2022-07-13 11:04:53.574] [renderer3] [error] [Extension Host] stderr: Jul. 13, 2022 11:04:53 A.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NoSuchMethodError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$createValidator$2(ModelValidator.java:204)
	at software.amazon.smithy.model.loader.ModelAssembler.validate(ModelAssembler.java:639)
	at software.amazon.smithy.model.loader.ModelAssembler.assemble(ModelAssembler.java:556)
	at software.amazon.smithy.lsp.SmithyInterface.readModel(SmithyInterface.java:69)
	at software.amazon.smithy.lsp.ext.SmithyProject.createModel(SmithyProject.java:177)
	at software.amazon.smithy.lsp.ext.SmithyProject.load(SmithyProject.java:165)
	at software.amazon.smithy.lsp.ext.SmithyProject.load(SmithyProject.java:142)
	at software.amazon.smithy.lsp.SmithyTextDocumentService.createProject(SmithyTextDocumentService.java:118)
	at software.amazon.smithy.lsp.SmithyTextDocumentService.createProject(SmithyTextDocumentService.java:154)
	at software.amazon.smithy.lsp.SmithyLanguageServer.lambda$loadSmithyBuild$0(SmithyLanguageServer.java:61)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at software.amazon.smithy.lsp.SmithyLanguageServer.loadSmithyBuild(SmithyLanguageServer.java:61)
	at software.amazon.smithy.lsp.SmithyLanguageServer.initialize(SmithyLanguageServer.java:70)
	... 16 more
Caused by: java.lang.NoSuchMethodError: 'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validateTrait(TraitBreakingChangesValidator.java:44)
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validate(TraitBreakingChangesValidator.java:36)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$null$0(ModelValidator.java:198)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

The only thing our fork does differently is related to publishing: we use a different tool (mill) to build and publish our fork. I guess this is related but I can't find the issue.

At first I thought that it was related to the version of the smithy model but after upgrading our fork to pull 1.22.0, it still works, so I guess this is not it.

Do you have anything in mind?

**Comment by daddykotex** [comment]
That's not true. I could reproduce.

It happens in one specific project and I have not been able to find why it happens. But I have more info: if I re-publish (locally) this repo under `0.2.0-SNAPSHOT` and use that in my extension, it loads fine. So I guess something with the older version is to blame.

Unfortunately the 0.1.0 release is not accompanied with a tag in the repo so it's hard to reproduce. I'll try to find out what's triggering the problem in my specific project.

**Comment by daddykotex** [comment]
Nevermind, it happens everywhere.

**Comment by daddykotex** [comment]
But this, still holds: **if I re-publish (locally) this repo under 0.2.0-SNAPSHOT and use that in my extension, it loads fine**

I'm pretty sure it's related to the version range the build.gradle

**Comment by daddykotex** [comment]
feel free to close this issue when the current version is published

**Comment by srchase** [comment]
`0.2.0` of the Language Server has been published: https://repo1.maven.org/maven2/software/amazon/smithy/smithy-language-server/0.2.0/
